---
- name: Check for compose file
  ansible.builtin.stat:
    path: /usr/lib/snipe/docker-compose.yaml
  register: compose_stat

- name: Compose exists
  when: compose_stat.stat.exists
  block:
    - name: Backup compose file
      ansible.builtin.copy:
        src: /usr/lib/snipe/docker-compose.yaml
        remote_src: true
        dest: /usr/lib/snipe/docker-compose.yaml.{{ ansible_facts.date_time.date }}@{{ ansible_facts.date_time.time }}~
        mode: u=rw,g=r,o=r
        owner: ctrmgr
        group: ctrmgr
      register: compose_backup_file
    - name: Teardown existing infrastructure
      community.docker.docker_compose_v2:
        project_src: /usr/lib/snipe
        state: absent

- name: Create directories
  ansible.builtin.file:
    path: /usr/lib/snipe
    state: directory
    mode: u=rw,g=r,o=r
    owner: ctrmgr
    group: ctrmgr

- name: Copy compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: /usr/lib/snipe/docker-compose.yaml
    mode: u=rw,g=,o=
    owner: ctrmgr
    group: ctrmgr

- name: Start new infrastructure
  community.docker.docker_compose_v2:
    project_src: /usr/lib/snipe
  ignore_errors: true
  register: new_infra

- name: Restore backup files
  when: new_infra.failed
  block:
    - name: Copy backup
      ansible.builtin.copy:
        src: "{{ compose_backup_file.dest }}"
        remote_src: true
        dest: /usr/lib/snipe/docker-compose.yaml
        mode: u=rw,g=,o=
        owner: ctrmgr
        group: ctrmgr
    - name: Remove backup
      ansible.builtin.file:
        path: "{{ compose_backup_file.dest }}"
        state: absent
