---
- name: Setup repository
  block:
    - name: Add repository key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: u=rw,g=,o=
        owner: root
        group: root
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570
    - name: Remove dearmored key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent
    - name: Dearmor repository key
      ansible.builtin.command:
        cmd: gpg -o /etc/apt/keyrings/docker.gpg --dearmor /etc/apt/keyrings/docker.asc
        creates: /etc/apt/keyrings/docker.gpg
    - name: Add repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Install packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Enable daemon
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started

- name: Install Ansible dependencies
  ansible.builtin.apt:
    name:
      - python3
      - python3-docker
      - python3-yaml
