name: Docker image

on:
  push:
    branches:
      - main
    paths:
      - docker/Dockerfile.snipe-app
      - .github/workflows/image.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: snipe-it
  VERSION: v6.3.1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=(v\d+.\d+.\d+),group=1,value=${{ env.VERSION }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: docker/
          file: docker/Dockerfile.snipe-app
          push: true
          no-cache: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ steps.meta.outputs.tags }}
